[launcher]
version = 0.3.2
description = Omada OC200 Add-on for Splunk

[id]
version = 0.3.2
name = ta_omada_oc200

[install]
build = 1789282094
is_configured = false
state = enabled

[package]
id = ta_omada_oc200
check_for_updates = true

[ui]
label = Omada OC200 Add-on for Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta_omada_oc200_settings = simple
reload.ta_omada_oc200_account = simple
