[devices]
python.version = python3
python.required = 3.9
index = default
interval = 60

[device_stats]
python.version = python3
python.required = 3.9
index = default
interval = 60

[clients]
python.version = python3
python.required = 3.9
index = default
interval = 60

[internet]
python.version = python3
python.required = 3.9
index = default
interval = 60

[client_stats]
python.version = python3
python.required = 3.9
index = default
interval = 60
