[admin:ta_omada_oc200_configuration]
match = /
members = ta_omada_oc200_account, ta_omada_oc200_settings

[admin:ta_omada_oc200_inputs]
match = /
members = ta_omada_oc200_client_stats, ta_omada_oc200_clients, ta_omada_oc200_device_stats, ta_omada_oc200_devices, ta_omada_oc200_internet

[admin:ta_omada_oc200_fields_devices]
match = /
members = ta_omada_oc200_fields_devices

[admin:ta_omada_oc200_fields_device_stats]
match = /
members = ta_omada_oc200_fields_device_stats

[admin:ta_omada_oc200_fields_clients]
match = /
members = ta_omada_oc200_fields_clients

[admin:ta_omada_oc200_fields_internet]
match = /
members = ta_omada_oc200_fields_internet

[admin:ta_omada_oc200_fields_client_stats]
match = /
members = ta_omada_oc200_fields_client_stats

[admin_external:ta_omada_oc200_account]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_omada_oc200_settings]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:ta_omada_oc200_devices]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_devices.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_omada_oc200_device_stats]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_device_stats.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_omada_oc200_clients]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_clients.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_omada_oc200_internet]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_internet.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_omada_oc200_client_stats]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_client_stats.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_omada_oc200_fields_devices]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_fields_devices.py
handleractions = list
handlerpersistentmode = true

[admin_external:ta_omada_oc200_fields_device_stats]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_fields_device_stats.py
handleractions = list
handlerpersistentmode = true

[admin_external:ta_omada_oc200_fields_clients]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_fields_clients.py
handleractions = list
handlerpersistentmode = true

[admin_external:ta_omada_oc200_fields_internet]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_fields_internet.py
handleractions = list
handlerpersistentmode = true

[admin_external:ta_omada_oc200_fields_client_stats]
handlertype = python
python.version = python3
python.required = 3.9
handlerfile = ta_omada_oc200_rh_fields_client_stats.py
handleractions = list
handlerpersistentmode = true
