[expose:ta_omada_oc200_account]
pattern = ta_omada_oc200_account
methods = POST, GET

[expose:ta_omada_oc200_account_specified]
pattern = ta_omada_oc200_account/*
methods = POST, GET, DELETE

[expose:ta_omada_oc200_settings]
pattern = ta_omada_oc200_settings
methods = POST, GET

[expose:ta_omada_oc200_settings_specified]
pattern = ta_omada_oc200_settings/*
methods = POST, GET, DELETE

[expose:ta_omada_oc200_devices]
pattern = ta_omada_oc200_devices
methods = POST, GET

[expose:ta_omada_oc200_devices_specified]
pattern = ta_omada_oc200_devices/*
methods = POST, GET, DELETE

[expose:ta_omada_oc200_device_stats]
pattern = ta_omada_oc200_device_stats
methods = POST, GET

[expose:ta_omada_oc200_device_stats_specified]
pattern = ta_omada_oc200_device_stats/*
methods = POST, GET, DELETE

[expose:ta_omada_oc200_clients]
pattern = ta_omada_oc200_clients
methods = POST, GET

[expose:ta_omada_oc200_clients_specified]
pattern = ta_omada_oc200_clients/*
methods = POST, GET, DELETE

[expose:ta_omada_oc200_internet]
pattern = ta_omada_oc200_internet
methods = POST, GET

[expose:ta_omada_oc200_internet_specified]
pattern = ta_omada_oc200_internet/*
methods = POST, GET, DELETE

[expose:ta_omada_oc200_client_stats]
pattern = ta_omada_oc200_client_stats
methods = POST, GET

[expose:ta_omada_oc200_client_stats_specified]
pattern = ta_omada_oc200_client_stats/*
methods = POST, GET, DELETE

[expose:ta_omada_oc200_fields_devices]
pattern = ta_omada_oc200_fields_devices
methods = GET

[expose:ta_omada_oc200_fields_device_stats]
pattern = ta_omada_oc200_fields_device_stats
methods = GET

[expose:ta_omada_oc200_fields_clients]
pattern = ta_omada_oc200_fields_clients
methods = GET

[expose:ta_omada_oc200_fields_internet]
pattern = ta_omada_oc200_fields_internet
methods = GET

[expose:ta_omada_oc200_fields_client_stats]
pattern = ta_omada_oc200_fields_client_stats
methods = GET

[expose:data/indexes]
pattern = data/indexes
methods = GET
